name: Go CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    name: Lint Code
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'Merge pull request') && !startsWith(github.event.head_commit.message, 'ci:')"
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Use Go 1.23.6
        uses: actions/setup-go@v4
        with:
          go-version: "1.23.6"

      - name: Install Go modules
        run: |
          go mod tidy
          go mod download

      - name: Install golangci-lint
        if: steps.golangci-lint-cache.outputs.cache-hit != 'true'
        run: |
          curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | \
            sh -s -- -b "$(go env GOPATH)"/bin v1.52.2

      - name: Run golangci-lint
        run: |
          golangci-lint run ./... --timeout=5m --skip-dirs '(^|/)(pkg/mod|opt/hostedtoolcache/go)($|/)'

  format:
    name: Format Code
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'Merge pull request') && !startsWith(github.event.head_commit.message, 'ci:')"
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Use Go 1.23.6
        uses: actions/setup-go@v4
        with:
          go-version: "1.23.6"

      - name: Install Go modules
        run: go mod download

      - name: Reformat Code
        run: |
          go fmt ./...

      - name: Run Go tests
        run: go test ./... -v
