name: Go CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint-and-format:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Extract Go version
        id: go-version
        run: |
          echo "go-version=$(grep '^go ' go.mod | awk '{print $2}')" >> $GITHUB_ENV

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ env.go-version }}

      - name: Install dependencies
        run: go mod download

      - name: Cache golangci-lint
        id: golangci-lint-cache
        uses: actions/cache@v3
        with:
          path: ~/.cache/golangci-lint
          key: ${{ runner.os }}-golangci-lint-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-golangci-lint-

      - name: Install golangci-lint
        if: steps.golangci-lint-cache.outputs.cache-hit != 'true'
        run: |
          curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | \
            sh -s -- -b $(go env GOPATH)/bin v1.52.2

      - name: Run golangci-lint
        run: golangci-lint run

      - name: Install gofumpt
        run: go install mvdan.cc/gofumpt@v0.6.0

      - name: Reformat code
        run: gofumpt -w .

  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Extract Go version
        id: go-version
        run: |
          echo "go-version=$(grep '^go ' go.mod | awk '{print $2}')" >> $GITHUB_ENV

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ env.go-version }}

      - name: Install OS dependencies (libxkbcommon, wayland, etc.)
        run: |
          sudo apt-get update
          sudo apt-get install -y pkg-config libxkbcommon-dev libwayland-dev

      - name: Install go modules
        run: go mod download

      - name: Run Go tests
        run: go test ./... -v
