name: Go CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    name: Lint Code
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'Merge pull request') && !startsWith(github.event.head_commit.message, 'ci:')"
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Use Go 1.23.6
        uses: actions/setup-go@v4
        with:
          go-version: "1.23.6"

      - name: Install Go modules
        run: |
          go mod tidy
          go mod download

      - name: Install golangci-lint
        if: steps.golangci-lint-cache.outputs.cache-hit != 'true'
        run: |
          curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | \
            sh -s -- -b "$(go env GOPATH)"/bin v1.52.2

      - name: Run golangci-lint
        run: |
          golangci-lint run ./... --fast --timeout=5m --skip-dirs '(^|/)(pkg/mod|opt/hostedtoolcache/go)($|/)'

  format:
    name: Run Formatting
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'Merge pull request') && !startsWith(github.event.head_commit.message, 'ci:')"
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Use Go 1.23.6
        uses: actions/setup-go@v4
        with:
          go-version: "1.23.6"

      - name: Install Go modules
        run: go mod download

      - name: Check Formatting
        run: |
          test -z "$(go fmt ./...)"

  test:
    name: Run Go Tests
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'Merge pull request') && !startsWith(github.event.head_commit.message, 'ci:')"
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Use Go 1.23.6
        uses: actions/setup-go@v4
        with:
          go-version: "1.23.6"

      - name: Install OS dependencies (pkg-config, xkbcommon, Wayland, Vulkan, X11)
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            golang \
            gcc \
            libgl1-mesa-dev \
            xorg-dev \
            libxkbcommon-dev

      - name: Install Go modules
        run: go mod download

      - name: Run Go tests
        run: go test ./... -v

  build-android:
    name: Build for Android
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'Merge pull request') && !startsWith(github.event.head_commit.message, 'ci:')"
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Use Go 1.23.6
        uses: actions/setup-go@v4
        with:
          go-version: "1.23.6"

      - name: Install OS dependencies (pkg-config, xkbcommon, Wayland, Vulkan, X11)
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            golang \
            gcc \
            libgl1-mesa-dev \
            xorg-dev \
            libxkbcommon-dev

      - name: Install Go modules
        run: go mod download

      - name: Install fyne cli
        run: go install fyne.io/fyne/v2/cmd/fyne@latest

      - name: Run Go tests
        run: make build-android
